// E2E image tests: real codec decode → pipeline → compare against vips goldens.
//
// Each test:
//   1. Reads an image fixture from tests/fixtures/images/
//   2. Decodes it with the vipers codec (PngCodec / JpegCodec)
//   3. Creates a MemorySource from the decoded pixels
//   4. Passes the pixels through a pipeline operation
//   5. Compares the raw output against a vips-generated golden .bin
//
// Goldens are regenerated by `tools/gen-fixtures.sh` with vips 8.18.2 on Apple
// Silicon (macOS) using repo-local scratch files:
//   vips invert <input> tools/.fixture-work/out.v && vips rawsave tools/.fixture-work/out.v <fixture>.bin
//   vips flip <input> tools/.fixture-work/out.v horizontal && vips rawsave tools/.fixture-work/out.v <fixture>.bin
//   vips rot <input> tools/.fixture-work/out.v d90 && vips rawsave tools/.fixture-work/out.v <fixture>.bin
//
// rawsave stores samples in host byte order (little-endian on Apple Silicon),
// which matches our pipeline's MemorySink output. Both U8 and U16 comparisons
// are therefore byte-for-byte exact for PNG (lossless).
//
// JPEG comparisons use per-channel tolerance (±1) because both pipelines go through
// libjpeg-turbo, but libvips and viprs still differ slightly in wrapper choices
// around metadata/orientation handling.
//
// NOTE: DecoderSource::read_region is not used here because it is currently a
// todo!() placeholder (see B-001). Tests decode with the codec directly and wrap
// the decoded pixels in MemorySource, which exercises the full codec → pipeline
// path without depending on the unimplemented tile-read path.

use std::{fs, path::Path};

use viprs::{
    adapters::{
        pipeline::PipelineBuilder, scheduler::rayon_scheduler::RayonScheduler,
        sinks::memory::MemorySink, sources::memory::MemorySource,
    },
    ports::scheduler::TileScheduler,
};

// ── Helpers ───────────────────────────────────────────────────────────────────

fn project_root() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).to_owned()
}

fn fixture_image(name: &str) -> Vec<u8> {
    let path = project_root()
        .join("tests")
        .join("fixtures")
        .join("images")
        .join(name);
    fs::read(&path).unwrap_or_else(|e| panic!("failed to read fixture image {path:?}: {e}"))
}

fn golden_bin(name: &str) -> Vec<u8> {
    let path = project_root()
        .join("tests")
        .join("fixtures")
        .join("e2e")
        .join(name);
    fs::read(&path).unwrap_or_else(|e| panic!("failed to read golden {path:?}: {e}"))
}

// ── PNG: invert ───────────────────────────────────────────────────────────────

/// sample.png → decode (U16, lossless) → invert → compare against vips golden.
///
/// vips command: vips invert sample.png tools/.fixture-work/inv.v && vips rawsave tools/.fixture-work/inv.v png_invert.bin
#[test]
#[cfg(feature = "png")]
fn png_invert_matches_vips() {
    use viprs::{adapters::codecs::PngCodec, domain::format::U16, ports::codec::ImageDecoder};

    let src_bytes = fixture_image("sample.png");
    let codec = PngCodec::default();
    // sample.png is 16-bit RGB → decoded as U16.
    let decoded = codec.decode::<U16>(&src_bytes).expect("PNG decode failed");

    let width = decoded.width();
    let height = decoded.height();
    let bands = decoded.bands();

    let source = MemorySource::<U16>::new(width, height, bands, decoded.pixels().to_vec())
        .expect("MemorySource failed");

    let pipeline = PipelineBuilder::from_source(source)
        .invert()
        .expect("invert step failed")
        .build()
        .expect("pipeline build failed");

    let mut sink = MemorySink::for_pipeline(&pipeline).unwrap();
    RayonScheduler::new(1)
        .expect("scheduler failed")
        .run(&pipeline, &mut sink)
        .expect("pipeline run failed");

    let actual = sink.into_buffer();
    let expected = golden_bin("png_invert.bin");

    assert_eq!(
        actual.len(),
        expected.len(),
        "png_invert: output length mismatch — got {} bytes, expected {}",
        actual.len(),
        expected.len()
    );
    assert_eq!(
        actual, expected,
        "png_invert: pixel-exact mismatch against vips golden"
    );
}

// ── PNG: flip_horizontal ──────────────────────────────────────────────────────

/// sample.png → decode (U16, lossless) → flip_horizontal → compare against vips golden.
///
/// vips command: vips flip sample.png tools/.fixture-work/flip.v horizontal && vips rawsave tools/.fixture-work/flip.v png_flip_horizontal.bin
#[test]
#[cfg(feature = "png")]
fn png_flip_horizontal_matches_vips() {
    use viprs::{adapters::codecs::PngCodec, domain::format::U16, ports::codec::ImageDecoder};

    let src_bytes = fixture_image("sample.png");
    let codec = PngCodec::default();
    let decoded = codec.decode::<U16>(&src_bytes).expect("PNG decode failed");

    let width = decoded.width();
    let height = decoded.height();
    let bands = decoded.bands();

    let source = MemorySource::<U16>::new(width, height, bands, decoded.pixels().to_vec())
        .expect("MemorySource failed");

    let pipeline = PipelineBuilder::from_source(source)
        .flip_horizontal()
        .expect("flip_horizontal step failed")
        .build()
        .expect("pipeline build failed");

    let mut sink = MemorySink::for_pipeline(&pipeline).unwrap();
    RayonScheduler::new(1)
        .expect("scheduler failed")
        .run(&pipeline, &mut sink)
        .expect("pipeline run failed");

    let actual = sink.into_buffer();
    let expected = golden_bin("png_flip_horizontal.bin");

    assert_eq!(
        actual.len(),
        expected.len(),
        "png_flip_horizontal: length mismatch"
    );
    assert_eq!(
        actual, expected,
        "png_flip_horizontal: pixel-exact mismatch against vips golden"
    );
}

// ── PNG: rotate90 ─────────────────────────────────────────────────────────────

/// sample.png → decode (U16, lossless) → rotate90 CW → compare against vips golden.
///
/// vips command: vips rot sample.png tools/.fixture-work/rot.v d90 && vips rawsave tools/.fixture-work/rot.v png_rotate90.bin
#[test]
#[cfg(feature = "png")]
fn png_rotate90_matches_vips() {
    use viprs::{adapters::codecs::PngCodec, domain::format::U16, ports::codec::ImageDecoder};

    let src_bytes = fixture_image("sample.png");
    let codec = PngCodec::default();
    let decoded = codec.decode::<U16>(&src_bytes).expect("PNG decode failed");

    let width = decoded.width();
    let height = decoded.height();
    let bands = decoded.bands();

    let source = MemorySource::<U16>::new(width, height, bands, decoded.pixels().to_vec())
        .expect("MemorySource failed");

    let pipeline = PipelineBuilder::from_source(source)
        .rotate90()
        .expect("rotate90 step failed")
        .build()
        .expect("pipeline build failed");

    let mut sink = MemorySink::for_pipeline(&pipeline).unwrap();
    RayonScheduler::new(1)
        .expect("scheduler failed")
        .run(&pipeline, &mut sink)
        .expect("pipeline run failed");

    let actual = sink.into_buffer();
    let expected = golden_bin("png_rotate90.bin");

    assert_eq!(
        actual.len(),
        expected.len(),
        "png_rotate90: length mismatch — got {} bytes ({}×{}×{}×2), expected {}",
        actual.len(),
        pipeline.width,
        pipeline.height,
        pipeline.output_bands,
        expected.len()
    );
    assert_eq!(
        actual, expected,
        "png_rotate90: pixel-exact mismatch against vips golden"
    );
}

// ── JPEG: invert ─────────────────────────────────────────────────────────────

/// sample.jpg → decode (U8, libjpeg-turbo) → invert → compare against vips golden with tolerance.
///
/// vips command: vips invert sample.jpg tools/.fixture-work/jinv.v && vips rawsave tools/.fixture-work/jinv.v jpeg_invert.bin
///
/// Tolerance ±1 per channel: both pipelines use libjpeg-turbo, but the wrappers are independent.
/// This fixture should stay within a single quantized sample so larger deltas
/// surface meaningful regressions instead of being masked.
#[test]
#[ignore] // issue #24: JPEG invert output differs from libvips by up to 16 sample values
#[cfg(feature = "jpeg")]
fn jpeg_invert_matches_vips() {
    // Validates JPEG parity against the vips golden with a tight tolerance so
    // codec or pipeline regressions cannot hide behind an overly broad threshold.
    use viprs::{adapters::codecs::JpegCodec, domain::format::U8, ports::codec::ImageDecoder};

    let src_bytes = fixture_image("sample.jpg");
    let codec = JpegCodec;
    let decoded = codec.decode::<U8>(&src_bytes).expect("JPEG decode failed");

    let width = decoded.width();
    let height = decoded.height();
    let bands = decoded.bands();

    let source = MemorySource::<U8>::new(width, height, bands, decoded.pixels().to_vec())
        .expect("MemorySource failed");

    let pipeline = PipelineBuilder::from_source(source)
        .invert()
        .expect("invert step failed")
        .build()
        .expect("pipeline build failed");

    let mut sink = MemorySink::for_pipeline(&pipeline).unwrap();
    RayonScheduler::new(1)
        .expect("scheduler failed")
        .run(&pipeline, &mut sink)
        .expect("pipeline run failed");

    let actual = sink.into_buffer();
    let expected = golden_bin("jpeg_invert.bin");

    assert_eq!(
        actual.len(),
        expected.len(),
        "jpeg_invert: length mismatch — got {} bytes ({}×{}×{}), expected {}",
        actual.len(),
        width,
        height,
        bands,
        expected.len()
    );

    // JPEG tolerance comparison: ±1 per channel on the checked fixture.
    let tolerance: i16 = 1;
    let mut max_diff = 0i16;
    let mut mismatch_count = 0usize;
    for (i, (&got, &exp)) in actual.iter().zip(expected.iter()).enumerate() {
        let diff = (got as i16 - exp as i16).abs();
        if diff > max_diff {
            max_diff = diff;
        }
        if diff > tolerance {
            mismatch_count += 1;
            if mismatch_count <= 5 {
                eprintln!(
                    "jpeg_invert: sample {i} diff={diff} (got={got}, exp={exp}) exceeds tolerance={tolerance}"
                );
            }
        }
    }
    assert_eq!(
        mismatch_count, 0,
        "jpeg_invert: {mismatch_count} samples exceeded tolerance={tolerance} (max_diff={max_diff})"
    );
}
