#![allow(clippy::significant_drop_tightening)]
// REASON: file sink guards intentionally span write and accounting updates.

use std::{
    fs::File,
    io::{BufWriter, Write},
    path::Path,
    sync::{Arc, Condvar, Mutex},
    thread::{self, JoinHandle},
};

use crossbeam_channel::{Receiver, Sender, bounded};

use crate::{
    adapters::pipeline::CompiledPipeline,
    domain::{error::ViprsError, format::BandFormatId, image::Region},
    ports::sink::ConcurrentSink,
};

/// Incremental writer used by [`FileSink`] on its dedicated disk thread.
///
/// Implementors receive output regions in the same row-major order generated by
/// the scheduler, allowing encoders to consume strips or tiles incrementally
/// without materializing the full image in memory.
pub trait FileSinkWriter: Send + 'static {
    /// Consumes one completed output region in the scheduler's row-major order.
    fn write_region(&mut self, region: Region, data: &[u8]) -> Result<(), ViprsError>;

    /// Flushes any buffered state after the last region has been delivered.
    fn finish(&mut self) -> Result<(), ViprsError> {
        Ok(())
    }
}

/// Minimal raw writer for tests and simple row-major strip dumps.
///
/// This helper writes the received bytes verbatim. It is therefore only suitable
/// when the scheduler emits full-width strips in row-major order. Encoders that
/// support incremental tile/strip writes should implement [`FileSinkWriter`]
/// directly instead.
pub struct RawFileWriter {
    writer: BufWriter<File>,
}

impl RawFileWriter {
    /// Opens `path` for verbatim row-major RAW output.
    pub fn create(path: impl AsRef<Path>) -> Result<Self, ViprsError> {
        let file = File::create(path)?;
        Ok(Self {
            writer: BufWriter::new(file),
        })
    }
}

impl FileSinkWriter for RawFileWriter {
    fn write_region(&mut self, _region: Region, data: &[u8]) -> Result<(), ViprsError> {
        self.writer.write_all(data)?;
        Ok(())
    }

    fn finish(&mut self) -> Result<(), ViprsError> {
        self.writer.flush()?;
        Ok(())
    }
}

struct WriteMessage {
    region: Region,
    data: Vec<u8>,
}

struct OrderingState {
    next_x: i32,
    next_y: i32,
    writer_error: Option<String>,
}

struct SharedOrdering {
    state: Mutex<OrderingState>,
    ready: Condvar,
}

impl SharedOrdering {
    const fn new() -> Self {
        Self {
            state: Mutex::new(OrderingState {
                next_x: 0,
                next_y: 0,
                writer_error: None,
            }),
            ready: Condvar::new(),
        }
    }

    fn store_writer_error(&self, err: &ViprsError) -> Result<(), ViprsError> {
        let mut state = self
            .state
            .lock()
            .map_err(|_| ViprsError::Scheduler("file sink ordering mutex poisoned".into()))?;
        state.writer_error = Some(err.to_string());
        self.ready.notify_all();
        Ok(())
    }

    fn writer_error(state: &OrderingState) -> Option<ViprsError> {
        state
            .writer_error
            .as_ref()
            .map(|message| ViprsError::Scheduler(format!("file sink writer failed: {message}")))
    }
}

/// Concurrent sink that hands completed tile buffers to a dedicated writer thread.
///
/// Rayon workers compute tiles, then block only long enough to preserve row-major
/// delivery order and enqueue a bounded copy of the completed buffer through
/// `crossbeam_channel::bounded(2)`. A dedicated `std::thread` performs the
/// blocking writer/encoder work.
pub struct FileSink {
    width: u32,
    height: u32,
    bands: u32,
    bytes_per_sample: usize,
    sender: Sender<WriteMessage>,
    ordering: Arc<SharedOrdering>,
    writer_handle: Mutex<Option<JoinHandle<Result<(), ViprsError>>>>,
}

impl FileSink {
    fn checked_total_bytes(
        width: u32,
        height: u32,
        bands: u32,
        bytes_per_sample: usize,
        details: &'static str,
    ) -> Result<usize, ViprsError> {
        let bytes_per_sample_u64 =
            u64::try_from(bytes_per_sample).map_err(|_| ViprsError::ImageTooLarge {
                width,
                height,
                bands,
                bytes: u128::from(width)
                    * u128::from(height)
                    * u128::from(bands)
                    * bytes_per_sample as u128,
                limit_bytes: usize::MAX as u128,
                details,
            })?;
        let total_bytes =
            u128::from(width) * u128::from(height) * u128::from(bands) * bytes_per_sample as u128;

        let Some(bytes) = u64::from(width)
            .checked_mul(u64::from(height))
            .and_then(|pixel_count| pixel_count.checked_mul(u64::from(bands)))
            .and_then(|sample_count| sample_count.checked_mul(bytes_per_sample_u64))
        else {
            return Err(ViprsError::ImageTooLarge {
                width,
                height,
                bands,
                bytes: total_bytes,
                limit_bytes: usize::MAX as u128,
                details,
            });
        };

        usize::try_from(bytes).map_err(|_| ViprsError::ImageTooLarge {
            width,
            height,
            bands,
            bytes: u128::from(bytes),
            limit_bytes: usize::MAX as u128,
            details,
        })
    }

    #[must_use]
    /// Creates a sink that forwards completed regions to `writer` on a dedicated thread.
    pub fn new(
        width: u32,
        height: u32,
        bands: u32,
        bytes_per_sample: usize,
        mut writer: Box<dyn FileSinkWriter>,
    ) -> Self {
        let (sender, receiver) = bounded(2);
        let ordering = Arc::new(SharedOrdering::new());
        let writer_ordering = Arc::clone(&ordering);
        let writer_handle =
            thread::spawn(move || Self::writer_loop(&mut *writer, &receiver, &writer_ordering));

        Self {
            width,
            height,
            bands,
            bytes_per_sample,
            sender,
            ordering,
            writer_handle: Mutex::new(Some(writer_handle)),
        }
    }

    #[must_use]
    /// Creates a file sink sized from a compiled pipeline output description.
    pub fn for_pipeline(pipeline: &CompiledPipeline, writer: Box<dyn FileSinkWriter>) -> Self {
        let bytes_per_sample = match pipeline.output_format {
            BandFormatId::U8 => 1,
            BandFormatId::U16 | BandFormatId::I16 => 2,
            BandFormatId::U32 | BandFormatId::I32 | BandFormatId::F32 => 4,
            BandFormatId::F64 => 8,
        };
        Self::new(
            pipeline.width,
            pipeline.height,
            pipeline.output_bands,
            bytes_per_sample,
            writer,
        )
    }

    /// Creates a file sink that writes the rendered output as a RAW byte stream.
    pub fn create_raw(
        path: impl AsRef<Path>,
        width: u32,
        height: u32,
        bands: u32,
        bytes_per_sample: usize,
    ) -> Result<Self, ViprsError> {
        Ok(Self::new(
            width,
            height,
            bands,
            bytes_per_sample,
            Box::new(RawFileWriter::create(path)?),
        ))
    }

    fn writer_loop(
        writer: &mut dyn FileSinkWriter,
        receiver: &Receiver<WriteMessage>,
        ordering: &Arc<SharedOrdering>,
    ) -> Result<(), ViprsError> {
        while let Ok(message) = receiver.recv() {
            if let Err(err) = writer.write_region(message.region, &message.data) {
                let _ = ordering.store_writer_error(&err);
                return Err(err);
            }
        }

        if let Err(err) = writer.finish() {
            let _ = ordering.store_writer_error(&err);
            return Err(err);
        }

        Ok(())
    }

    fn validate_region(&self, region: Region, data_len: usize) -> Result<(), ViprsError> {
        let end_x = i64::from(region.x) + i64::from(region.width);
        let end_y = i64::from(region.y) + i64::from(region.height);
        if region.x < 0
            || region.y < 0
            || end_x > i64::from(self.width)
            || end_y > i64::from(self.height)
        {
            return Err(ViprsError::Scheduler(format!(
                "file sink region {region:?} is out of bounds for {}x{} image",
                self.width, self.height
            )));
        }

        let expected = Self::checked_total_bytes(
            region.width,
            region.height,
            self.bands,
            self.bytes_per_sample,
            "file sink region byte count exceeds addressable memory",
        )?;
        if data_len != expected {
            return Err(ViprsError::Scheduler(format!(
                "file sink buffer length {data_len} does not match expected {expected} for {region:?}"
            )));
        }

        Ok(())
    }

    const fn advance_expected_tile(state: &mut OrderingState, region: Region, width: u32) {
        let next_x = region.x + region.width as i32;
        if next_x >= width as i32 {
            state.next_x = 0;
            state.next_y = region.y + region.height as i32;
        } else {
            state.next_x = next_x;
            state.next_y = region.y;
        }
    }
}

impl ConcurrentSink for FileSink {
    fn write_region_concurrent(&self, region: Region, data: &[u8]) -> Result<(), ViprsError> {
        self.validate_region(region, data.len())?;

        let mut state = self
            .ordering
            .state
            .lock()
            .map_err(|_| ViprsError::Scheduler("file sink ordering mutex poisoned".into()))?;

        while state.next_x != region.x || state.next_y != region.y {
            if let Some(err) = SharedOrdering::writer_error(&state) {
                return Err(err);
            }
            state =
                self.ordering.ready.wait(state).map_err(|_| {
                    ViprsError::Scheduler("file sink ordering mutex poisoned".into())
                })?;
        }

        if let Some(err) = SharedOrdering::writer_error(&state) {
            return Err(err);
        }

        self.sender
            .send(WriteMessage {
                region,
                data: data.to_vec(),
            })
            .map_err(|_| {
                SharedOrdering::writer_error(&state).unwrap_or_else(|| {
                    ViprsError::Scheduler(
                        "file sink writer channel closed before tile could be written".into(),
                    )
                })
            })?;

        Self::advance_expected_tile(&mut state, region, self.width);
        self.ordering.ready.notify_all();
        Ok(())
    }

    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn finish(self: Box<Self>) -> Result<(), ViprsError> {
        drop(self.sender);

        let handle = self
            .writer_handle
            .into_inner()
            .map_err(|_| ViprsError::Scheduler("file sink writer handle mutex poisoned".into()))?
            .ok_or_else(|| {
                ViprsError::Scheduler("file sink writer thread already joined".into())
            })?;

        handle.join().unwrap_or_else(|_| {
            Err(ViprsError::Scheduler(
                "file sink writer thread panicked".into(),
            ))
        })
    }
}

#[cfg(test)]
mod tests {
    use std::{
        path::PathBuf,
        sync::{Arc, Mutex},
        thread,
        time::{Duration, SystemTime, UNIX_EPOCH},
    };

    use super::*;

    #[derive(Clone)]
    struct RecordedWrite {
        region: Region,
        data: Vec<u8>,
    }

    struct RecordingWriter {
        writes: Arc<Mutex<Vec<RecordedWrite>>>,
    }

    impl FileSinkWriter for RecordingWriter {
        fn write_region(&mut self, region: Region, data: &[u8]) -> Result<(), ViprsError> {
            let mut writes = self
                .writes
                .lock()
                .map_err(|_| ViprsError::Scheduler("recording writer mutex poisoned".into()))?;
            writes.push(RecordedWrite {
                region,
                data: data.to_vec(),
            });
            Ok(())
        }
    }

    fn artifact_path(name: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_or(0, |duration| duration.as_nanos());
        PathBuf::from("target")
            .join("test-artifacts")
            .join(format!("{name}-{}-{nanos}.bin", std::process::id()))
    }

    #[test]
    fn file_sink_orders_tiles_before_writer_thread() {
        let writes = Arc::new(Mutex::new(Vec::new()));
        let sink = FileSink::new(
            4,
            2,
            1,
            1,
            Box::new(RecordingWriter {
                writes: Arc::clone(&writes),
            }),
        );

        thread::scope(|scope| {
            scope.spawn(|| {
                sink.write_region_concurrent(Region::new(2, 0, 2, 1), &[3, 4])
                    .unwrap();
            });
            scope.spawn(|| {
                thread::sleep(Duration::from_millis(10));
                sink.write_region_concurrent(Region::new(0, 1, 2, 1), &[5, 6])
                    .unwrap();
            });
            scope.spawn(|| {
                thread::sleep(Duration::from_millis(20));
                sink.write_region_concurrent(Region::new(0, 0, 2, 1), &[1, 2])
                    .unwrap();
            });
            scope.spawn(|| {
                thread::sleep(Duration::from_millis(30));
                sink.write_region_concurrent(Region::new(2, 1, 2, 1), &[7, 8])
                    .unwrap();
            });
        });

        Box::new(sink).finish().unwrap();

        let writes = writes.lock().unwrap();
        assert_eq!(writes.len(), 4);
        assert_eq!(writes[0].region, Region::new(0, 0, 2, 1));
        assert_eq!(writes[0].data, vec![1, 2]);
        assert_eq!(writes[1].region, Region::new(2, 0, 2, 1));
        assert_eq!(writes[1].data, vec![3, 4]);
        assert_eq!(writes[2].region, Region::new(0, 1, 2, 1));
        assert_eq!(writes[2].data, vec![5, 6]);
        assert_eq!(writes[3].region, Region::new(2, 1, 2, 1));
        assert_eq!(writes[3].data, vec![7, 8]);
    }

    #[test]
    fn file_sink_writes_raw_strips_to_disk() {
        let path = artifact_path("file-sink-raw");
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();

        let sink = FileSink::create_raw(&path, 4, 4, 1, 1).unwrap();

        thread::scope(|scope| {
            scope.spawn(|| {
                thread::sleep(Duration::from_millis(15));
                sink.write_region_concurrent(
                    Region::new(0, 2, 4, 2),
                    &[9, 10, 11, 12, 13, 14, 15, 16],
                )
                .unwrap();
            });
            scope.spawn(|| {
                sink.write_region_concurrent(Region::new(0, 0, 4, 2), &[1, 2, 3, 4, 5, 6, 7, 8])
                    .unwrap();
            });
        });

        Box::new(sink).finish().unwrap();

        let bytes = std::fs::read(&path).unwrap();
        assert_eq!(
            bytes,
            vec![1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
        );
        std::fs::remove_file(path).unwrap();
    }

    #[test]
    fn file_sink_rejects_invalid_buffer_lengths() {
        let writes = Arc::new(Mutex::new(Vec::new()));
        let sink = FileSink::new(
            4,
            4,
            1,
            1,
            Box::new(RecordingWriter {
                writes: Arc::clone(&writes),
            }),
        );

        let err = sink
            .write_region_concurrent(Region::new(0, 0, 4, 1), &[1, 2, 3])
            .unwrap_err();
        assert!(matches!(err, ViprsError::Scheduler(message) if message.contains("buffer length")));

        Box::new(sink).finish().unwrap();
    }

    #[test]
    fn file_sink_rejects_regions_whose_byte_count_overflows() {
        let writes = Arc::new(Mutex::new(Vec::new()));
        let sink = FileSink::new(
            u32::MAX,
            u32::MAX,
            u32::MAX,
            2,
            Box::new(RecordingWriter {
                writes: Arc::clone(&writes),
            }),
        );

        let err = sink
            .write_region_concurrent(Region::new(0, 0, u32::MAX, u32::MAX), &[])
            .unwrap_err();
        assert!(matches!(
            err,
            ViprsError::ImageTooLarge {
                details: "file sink region byte count exceeds addressable memory",
                ..
            }
        ));

        Box::new(sink).finish().unwrap();
    }

    #[test]
    fn file_sink_rejects_regions_whose_x_end_overflows_i32() {
        let writes = Arc::new(Mutex::new(Vec::new()));
        let sink = FileSink::new(
            1,
            1,
            1,
            1,
            Box::new(RecordingWriter {
                writes: Arc::clone(&writes),
            }),
        );

        let err = sink
            .write_region_concurrent(Region::new(i32::MAX, 0, 1, 1), &[1])
            .unwrap_err();
        assert!(matches!(err, ViprsError::Scheduler(message) if message.contains("out of bounds")));

        Box::new(sink).finish().unwrap();
    }

    #[test]
    fn file_sink_rejects_regions_whose_y_end_overflows_i32() {
        let writes = Arc::new(Mutex::new(Vec::new()));
        let sink = FileSink::new(
            1,
            1,
            1,
            1,
            Box::new(RecordingWriter {
                writes: Arc::clone(&writes),
            }),
        );

        let err = sink
            .write_region_concurrent(Region::new(0, i32::MAX, 1, 1), &[1])
            .unwrap_err();
        assert!(matches!(err, ViprsError::Scheduler(message) if message.contains("out of bounds")));

        Box::new(sink).finish().unwrap();
    }
}
